title: Tic Tac Logic
subtitle: Geração de Tabuleiros com Solução Única
subject: Laboratórios de Informática II
date: Junho 2018
# logo: EEUM.png
author: [Nelson Estevão, Pedro Ribeiro, Rui Mendes]
  # - name: Nelson Estevão
  #   number: A76434
  #   avatar: nelson.jpeg
  # - name: Pedro Ribeiro
  #   number: A85493
  #   avatar: pedro.jpeg
  # - name: Rui Mendes
  #   number: A83712
  #   avatar: rui.jpeg
keywords: [C, CGIs]
lang: pt-PT
toc: true
numbersections: true
# geometry: margin=2.5cm
titlepage: true
# titlepage-color: FFFFFF
# titlepage-text-color: FFFFFF
# titlepage-rule-color: 360049
# titlepage-rule-height: 0
# titlepage-background: figures/background.pdf
