title: Redes de Computadores
subtitle: Protocolo IPv4
logo: EEUM.png
author:
  - name: Hugo Carvalho
    number: A85579
    avatar: hugo.jpeg
  - name: Nelson Estevão
    number: A76434
    avatar: nelson.jpeg
  - name: Pedro Ribeiro
    number: A85493
    avatar: pedro.jpeg
  - name: Ricardo Silva
    number: A84123
    avatar: ricardo.jpeg
  - name: Rui Mendes
    number: A83712
    avatar: rui.jpeg
keywords: [IPv4, Networks]
lang: pt-PT
fontsize: 11pt
toc: true
numbersections: true
geometry: margin=2.5cm
titlepage: true
